### ISSUE TITLE
[Window] Command group menus do not close after a second window has been closed

### ISSUE THREAD

**Issue by russellbanks** [kirill-grouchnikov/aurora#22]
### Bug Description

Normally, when a command group menu is open and the window is moved, the command group menu will close. However, if a second window is opened and then closed, the command group menu will no longer close when the window is moved and will rather stay in place, as shown below.

For context, I am showing the second window through `var isAboutWindowOpen by remember { mutableStateOf(false) }`.

### Steps to Reproduce

1. Open a second window and close it
2. Open a command group menu
3. Move the window

Actual Result:

The command group menu stays in place when the window is moved.

Expected Result:

The command group menu should close when the window is moved.

### Screenshots

![NVIDIA_Share_XhRlIV48ap](https://user-images.githubusercontent.com/74878137/162615536-1e5ab876-5ed0-4b74-853b-cbc1cde565d0.gif)

### Platform Info

Aurora Version: 1.1.0

Operating System: Windows 11

**Comment by russellbanks** [comment]
This issue still seems to be present on native, decorated windows:

![NVIDIA_Share_eQ1a7FC7Xy](https://user-images.githubusercontent.com/74878137/176043009-fab93f6d-1282-4190-a71d-dd7632e0c50b.gif)

Edit: a second window does not need to have been opened for this issue to be present, unlike the original post.

**Comment by kirill-grouchnikov** [comment]
I think I know why this is happening - in non-undecorated mode the window is using OS-provided title bar. So when you move the window by grabbing that title bar, right now Aurora doesn't get notified in its window-level AWT listener, and the popups like menus, combos etc don't get dismissed.

**Comment by kirill-grouchnikov** [comment]
Ugh, this is not going to be easy to fix.

[Over here](https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/javax/swing/plaf/basic/BasicPopupMenuUI.java#L790) this is how Swing's popup menu registers itself to get notified on window ungrabbing. Note that it's using internal, undocumented and inaccessible event mask. Then [over here](https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/javax/swing/plaf/basic/BasicPopupMenuUI.java#L861) it gets notified that the window has been ungrabbed so that it can hide itself. Again, internal and inaccessible event class. And there's also [these APIs](https://github.com/openjdk/jdk/blob/master/src/java.desktop/share/classes/sun/awt/SunToolkit.java#L1641) to grab / ungrab windows to have the whole process rolling.

None of which can be used, especially now that the JDK is heavily restricting access to such internal APIs.
