### ISSUE TITLE
Create alpha/beta/RC release

### ISSUE THREAD

**Issue by russellbanks** [kirill-grouchnikov/aurora#40]
Currently my app is relying on Aurora snapshot because of the necessary bug fixes and the implementation of tabs, etc. However, it's not great to be using a snapshot in production as this can cause breaking changes at any time. Therefore, whilst it might not be suitable for a full release as Jetbrains Compose 1.2.0 is still in beta, could we get an alpha/beta/RC release, so that this can be a more stable dependency, but include the latest fixes and features.

**Comment by kirill-grouchnikov** [comment]
This is unlikely to happen with Aurora (or Radiance) since I would be promising something that I'm not going to be able to deliver on.

I want to have a space in which I can break backwards compatibility all through the specific development cycle, as well as between any releases. I understand that this may not work for some codebases, but that is not going to change even if I added beta / RC labels onto it.

It is a bit unfortunate that we are early enough in the Compose release cycle itself where there's a lot of new core development still going on, and that the community expects all the libraries to keep up with the Kotlin releases (this one may get a bit easier now with the unbundled compiler plugin release cycles). There's also the underlying Skia updates to be considered (which do break backwards compatibility, and that propagates upwards to Aurora via Skiko).

It looks like for at least the medium-term future, Aurora releases will be tied to Compose for Desktop releases. I may or may not wish for those to be more frequent, but that is not something that I can control. And staying on older CfD releases is probably not something that will happen in Aurora for a while.

**Comment by kirill-grouchnikov** [comment]
Having said, that, specifically for 1.2, the only thing that will require changes in Aurora would be if [this issue](https://github.com/JetBrains/compose-jb/issues/2237) gets fixed in the final CfD 1.2 build. It is very unlikely that it will need breaking Aurora changes though, as that is only for the visuals of popup borders which is an internal implementation detail.

So pretty much Aurora 1.2 is in its "beta" state if you're asking to "map" it to what Compose is using.

**Comment by kirill-grouchnikov** [comment]
Version 1.2.0 will be uploaded to Maven tonight
