### ISSUE TITLE
[Component] `textAlign = TextAlign.Center` aligns text to the center-right

### ISSUE THREAD

**Issue by russellbanks** [kirill-grouchnikov/aurora#74]
I've just migrated my project to Aurora 2.0 so I can stay up to date with the latest improvements and the text alignment for one of my buttons that had `textAlign = TextAlign.Center` is now aligned to the center-right.

![java_20huv0lLPq](https://user-images.githubusercontent.com/74878137/236842571-b11ed60b-5bd5-4417-8dbd-72b767a59fe7.png)

```kotlin
CommandButtonProjection(
    contentModel = Command(text = "Restart", action = window::restart),
    presentationModel = CommandButtonPresentationModel(
        textStyle = TextStyle(fontSize = 12.sp, textAlign = TextAlign.Center),
        horizontalGapScaleFactor = 1.8f,
        verticalGapScaleFactor = 1.5f
    )
).project(Modifier.width(140.dp).padding(6.dp))
```

Removing `textAlign = TextAlign.Center` fixes this, but I would expect it to have done the above, like before.

![java_gYN2m6WKQd](https://user-images.githubusercontent.com/74878137/236842797-4711397d-45d0-4f43-af98-0df09950c2c2.png)

**Comment by kirill-grouchnikov** [comment]
It might have worked before, but not intentionally. There's a lot of combinations of presence of the icon, presence of the popup arrow, content padding, button width that can't fit the entire text or button width that is wider than needed (like in your case) that make it complex to account for all possible cases.

To horizontally center button content, use `CommandButtonPresentationModel.horizontalAlignment` instead of setting it on the `TextStyle`. 

Things might look different once I can start using the new `TextMeasurer` API added in Compose 1.4, but I'm not planning to use it until it exits the experimental phase. Until then, don't set `textAlign` on the `textStyle`. Use `horizontalAlignment` on the button presentation model.
